@startuml
left to right direction
skinparam packageStyle rectangle
    actor administrator
    actor visitor
    
rectangle system{
    (database) <|. (install)
    administrator - (install)
    (user registratie) .|>  (database)
    visitor - (user registratie)
    visitor - (wishlist)
    (wishlist) -|> (user registratie)
    (database) <|. (wishlist)
}
note bottom of visitor
    Aannamen: De bezoeker gebruikt de nieuwste browser versie
    Interactie: De user registreerd zich voor deelname aan 1 of meer feest(en). 
    Uitzonderingen:
end note
@enduml

